### ISSUE TITLE
GET /cats loading the page twice

### ISSUE THREAD

**Issue by Jr-14** [Jr-14/cat-kit-web#11]
Upon loading the /cats route, we re-render twice 🤔 

![Image](https://github.com/user-attachments/assets/0b00eaec-cdbc-4c12-b51c-1306014e7111)

**Comment by jrequizo** [comment]
This is the expected behaviour on React when running in debug/dev mode. If you try it out on a build version, it won't render twice.

**Comment by jrequizo** [comment]
See https://stackoverflow.com/questions/61254372/my-react-component-is-rendering-twice-because-of-strict-mode

**Comment by jrequizo** [comment]
Marking as closed as initial issue resides with StrictMode. Will have to open a new issue or a feature request to memoize requests to prevent double-calls when navigating to /cats when already on /cats
